//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AML.REPORT.GENERATOR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTR_TRANSACTIONS
    {
        public string TRANSACTIONNUMBER { get; set; }
        public string TRANSACTION_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DATE_TRANSACTION { get; set; }
        public string TELLER { get; set; }
        public string AUTHORIZED { get; set; }
        public string LATE_DEPOSIT { get; set; }
        public Nullable<System.DateTime> DATE_POSTING { get; set; }
        public string TRANSMODE_CODE { get; set; }
        public decimal AMOUNT_LOCAL { get; set; }
        public string FROM_FUNDS_CODE { get; set; }
        public string FROM_FUNDS_COMMENTS { get; set; }
        public string FROM_INSTITUTION_NAME { get; set; }
        public string FROM_INSTITUTION_CODE { get; set; }
        public string FROM_ACCOUNT { get; set; }
        public string FROM_ACCOUNT_NAME { get; set; }
        public string FROM_COUNTRY { get; set; }
        public string TO_FUNDS_CODE { get; set; }
        public string TO_FUNDS_COMMENTS { get; set; }
        public string TO_INSTITUTION_NAME { get; set; }
        public string TO_INSTITUTION_CODE { get; set; }
        public string TO_BRANCH { get; set; }
        public string TO_ACCOUNT { get; set; }
        public string TO_CURRENCY_CODE { get; set; }
        public string TO_ACCOUNT_NAME { get; set; }
        public string TO_CLIENT_NUMBER { get; set; }
        public string PERSONAL_ACCOUNT_TYPE { get; set; }
        public string ENT_NAME { get; set; }
        public string ENT_INCORP_NO { get; set; }
        public string ENT_BUSINESS { get; set; }
        public string ENT_CONTACT_TYPE { get; set; }
        public string ENT_COMM_TYPE { get; set; }
        public string ENT_PHONE { get; set; }
        public string ENT_ADDRSS_TYPE { get; set; }
        public string ENT_ADDRESS { get; set; }
        public string ENT_CITY { get; set; }
        public string ENT_COUNTRY_CODE { get; set; }
        public string ENT_STATE { get; set; }
        public string ENT_INCORP_STATE { get; set; }
        public string ENT_INCORP_COUNTRY_CODE { get; set; }
        public string ENT_DIR_1ST_NAME { get; set; }
        public string ENT_DIR_LAST_NAME { get; set; }
        public string SIGNATORY_TITLE { get; set; }
        public string SIGNATORY_FIRST_NAME { get; set; }
        public string SIGNATORY_LAST_NAME { get; set; }
        public Nullable<System.DateTime> SIGNATORY_DOB { get; set; }
        public string SIGNATORY_NATIONALITY { get; set; }
        public string SIGNATORY_RESIDENCE { get; set; }
        public string SIGNATORY_OCCUPATION { get; set; }
        public Nullable<System.DateTime> TO_ACCT_OPENED { get; set; }
        public string TO_ACCT_BALANCE { get; set; }
        public string TO_ACCT_STATUS_CODE { get; set; }
        public string TO_ACCOUNT_COUNTRY { get; set; }
        public string CDI { get; set; }
        public string PRIMARY_MEDIUM { get; set; }
        public Nullable<int> DATE_KEY { get; set; }
        public string FROM_PERSON_FIRST_NAME { get; set; }
        public string FROM_PERSON_LAST_NAME { get; set; }
        public string TO_PERSON_FIRST_NAME { get; set; }
        public string TO_PERSON_LAST_NAME { get; set; }
        public Nullable<decimal> AMOUNT_FOREIGN { get; set; }
        public string CODE_FROM_TRANS { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string POLARIS_ACCOUNT { get; set; }
        public string BANK_CUST_BRANCH { get; set; }
        public string BANK_CUST_NAME { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_CODE { get; set; }
        public string BANK_SWIFT_CODE { get; set; }
        public string EXTERNAL_ACC { get; set; }
    }
}
