//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AML.REPORT.GENERATOR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT_ENTITY
    {
        public string RENTITY_ID { get; set; }
        public string SUBMISSION_CODE { get; set; }
        public string REPORT_CODE { get; set; }
        public System.DateTime SUBMISSION_DATE { get; set; }
        public string CURRENCY_CODE_LOCAL { get; set; }
        public string GENDER { get; set; }
        public string E_TITLE { get; set; }
        public string E_FIRST_NAME { get; set; }
        public string E_MIDDLE_NAME { get; set; }
        public string E_LAST_NAME { get; set; }
        public System.DateTime E_BIRTHDATE { get; set; }
        public string BIRTH_PLACE { get; set; }
        public string MOTHERS_NAME { get; set; }
        public string PASSPORT_NUMBER { get; set; }
        public string PASSPORT_COUNTRY { get; set; }
        public Nullable<decimal> ID_NUMBER { get; set; }
        public string E_NATIONALITY1 { get; set; }
        public string RESISDENCE { get; set; }
        public string TPH_CONTACT_TYPE { get; set; }
        public string TPH_COMMUNICATION_TYPE { get; set; }
        public string TPH_NUMBER { get; set; }
        public string ADDRESS_TYPE { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string COUNTRY_STATE { get; set; }
        public string EMAIL { get; set; }
        public string OCCUPATION { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_ADDRESS_TYPE { get; set; }
        public string EMP_ADDRESS { get; set; }
        public string EMP_CITY { get; set; }
        public string EMP_COUNTRY_CODE { get; set; }
        public string EMP_COUNTRY_STATE { get; set; }
        public string EMP_TPH_CONTACT_TYPE { get; set; }
        public string EMP_TPH_COMMUNICATION_TYPE { get; set; }
        public string EMP_TPH_NUMBER { get; set; }
        public string SOURCE_OF_WEALTH { get; set; }
        public string REASON { get; set; }
        public string ACTION { get; set; }
    }
}
